# Generated by Django 4.2.1 on 2023-05-31 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howlong', models.IntegerField(max_length=2000)),
                ('toolong', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('NR', 'Not Really')], default=('NR', 'Not Really'), max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.book')),
            ],
        ),
    ]
