# Generated by Django 4.2.1 on 2023-05-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_pages_toolong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='howlong',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pages',
            name='toolong',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('NR', 'Not Really')], default=('NR', 'Not Really'), max_length=2),
        ),
    ]
