# Generated by Django 4.2.1 on 2023-05-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_pages_howlong_alter_pages_toolong'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='PageCount',
        ),
    ]
