# Generated by Django 4.2.1 on 2023-05-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_pages_pagecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Read')),
                ('pages', models.IntegerField(verbose_name='How many pages read')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.book')),
            ],
        ),
        migrations.DeleteModel(
            name='PageCount',
        ),
    ]
