# Generated by Django 4.2.1 on 2023-05-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_pagesread_delete_pagecount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagesRead',
            new_name='Page',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='pages',
            new_name='numpages',
        ),
    ]
