# Generated by Django 4.2.1 on 2023-05-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_page_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='numpages',
        ),
        migrations.AddField(
            model_name='chapter',
            name='numchapters',
            field=models.IntegerField(default=1, verbose_name='How many chapters read'),
        ),
    ]
