# Generated by Django 4.2.1 on 2023-06-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_chapter_numpages_chapter_numchapters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-date']},
        ),
    ]
