# Generated by Django 4.2.1 on 2023-06-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_bookstore_alter_chapter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
