# Generated by Django 4.2.1 on 2023-06-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_book_bookstore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookstore',
            new_name='bookstores',
        ),
    ]
